title: ZigUNO
description: Zigbee DIY device development board with CC2530 onboard compatible with all your Uno shields

email: xyzroe@mind.in.ua
avatar: https://avatars.githubusercontent.com/u/6440415?v=4
favicon: https://xyzroe.cc/favicon.ico
url: "https://xyzroe.cc"
remote_theme: sylhare/Type-on-Strap
cookie_consent: true
google_analytics: G-5JP6L4L4DL
color_theme: auto
footer_text: '<a rel="xyzroe" href="http://xyzroe.cc">xyzroe</a> © 2022-2024<br /><a rel="license" href="https://raw.githubusercontent.com/xyzroe/ZigUNO/main/LICENSE">GNU General Public License v3.0</a>'
plugins:
  - jekyll-remote-theme
